# Generated by Django 5.0 on 2024-03-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recognizer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.DeleteModel(
            name="Image_Path",
        ),
    ]
